[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mackechniealex_py_pkg"
version = "0.0.1"
authors = [
  { name="Alex Mackechnie", email="mackechniealex@gmail.com" },
]
description = "Alex Mackechnie test package."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/AlexMackechnie/scratchpad/tree/main/lang/python/packages/packaging_tutorial"